import {ensureFirebase,dbRef,onValue,get,set,update,remove} from "./firebase.js";
import {$,show,msg,activePlayers,numberText,phaseName} from "./app-common.js";
import {matrixSizeFor,makeCentralHoles,activeCells,buildRound} from "./game-engine.js";
import {RECOVERY_TTL_MS} from "./firebase-config.js";
let game={};
async function boot(){try{await ensureFirebase();$("#connection").textContent="Firebase 已連線";show("#dashboard");bind();onValue(dbRef("game"),s=>{game=s.val()||{};render();});}catch(e){$("#connection").textContent="Firebase 未連線";show("#setupMissing");msg(e.message,"error");}}
function bind(){
  $("#lockJoin").onclick=()=>update(dbRef("game/meta"),{joinLocked:true});$("#unlockJoin").onclick=()=>update(dbRef("game/meta"),{joinLocked:false});
  $("#startIntro").onclick=startIntro;$("#prevIntro").onclick=()=>moveIntro(-1);$("#nextIntro").onclick=()=>moveIntro(1);
  $("#buildR1").onclick=()=>startRound(1);$("#buildR2").onclick=()=>startRound(2);$("#makeRecovery").onclick=makeRecovery;$("#reset").onclick=resetAll;
}
function render(){const players=activePlayers(game),n=players.length,s=matrixSizeFor(n||1),holes=s*s-n;$("#playerCount").textContent=n;$("#phaseName").textContent=phaseName(game.meta?.phase);$("#matrixInfo").textContent=n?`${s} × ${s}｜挖空 ${holes} 格`:`—`;$("#players").innerHTML=players.map(p=>`<span class="player-chip">#${numberText(p.number)} ${p.name}</span>`).join("");const opts=players.map(p=>`<option value="${p.id}">#${numberText(p.number)} ${p.name}</option>`).join("");$("#recoverSelect").innerHTML=opts;const order=game.meta?.introOrder||[],cur=players.find(p=>p.id===order[game.meta?.introIndex||0]);$("#introNow").textContent=cur?`目前：#${numberText(cur.number)} ${cur.name}`:"尚未開始";}
async function startIntro(){const players=activePlayers(game);if(!players.length){msg("目前沒有玩家。","error");return;}await update(dbRef("game/meta"),{joinLocked:true,phase:"intro",introOrder:players.map(p=>p.id),introIndex:0});}
async function moveIntro(delta){const order=game.meta?.introOrder||[];if(!order.length)return;const next=Math.max(0,Math.min(order.length-1,(game.meta?.introIndex||0)+delta));await update(dbRef("game/meta"),{introIndex:next});}
async function startRound(rn){const players=activePlayers(game);if(players.length<4){msg("至少需要 4 位玩家才能開始。","error");return;}const size=matrixSizeFor(players.length);let holes=rn===2&&game.rounds?.[1]?.holes?game.rounds[1].holes:makeCentralHoles(size,size*size-players.length);if(activeCells(size,holes).length!==players.length){msg("盤面挖空計算異常，請重新操作。","error");return;}let round;for(let i=0;i<30;i++){try{round=buildRound(players,size,holes,rn);break;}catch{holes=makeCentralHoles(size,size*size-players.length);}}if(!round){msg("找不到符合兩個緊鄰條件的盤面。請調整人數後再試。","error");return;}const updates={};updates[`rounds/${rn}`]=round;updates[`meta/phase`]=rn===1?"round1":"round2";updates[`meta/round`]=rn;updates[`meta/matrixSize`]=size;updates[`meta/holes`]=holes;updates[`meta/joinLocked`]=true;await update(dbRef("game"),updates);msg(`ROUND ${rn} 已開始。`,"ok");}
async function makeRecovery(){const id=$("#recoverSelect").value,p=game.players?.[id];if(!p)return;let code="";for(let i=0;i<10;i++){code=String(Math.floor(100000+Math.random()*900000));const snap=await get(dbRef(`game/recovery/${code}`));if(!snap.exists())break;}await set(dbRef(`game/recovery/${code}`),{playerId:id,number:p.number,expiresAt:Date.now()+RECOVERY_TTL_MS,used:false});const box=$("#recoveryResult");box.innerHTML=`玩家 #${numberText(p.number)} 的恢復碼：<b style="font-size:2rem">${code}</b><br><span class="small">5 分鐘內有效，只能使用一次。</span>`;show(box);}
async function resetAll(){if(!confirm("確定要清空整場遊戲嗎？所有玩家與進度都會刪除。"))return;await remove(dbRef("game"));await set(dbRef("game/meta"),{phase:"lobby",joinLocked:false,nextNumber:0});msg("已清空整場遊戲。","ok");}
boot();
