import {ensureFirebase,dbRef,onValue,update} from "./firebase.js";
import {$,show,msg,activePlayers,numberText} from "./app-common.js";
import {evaluateSubmission} from "./game-engine.js";
let game={},selected=null,submission={},syncedRound=0,syncedCheck=0,syncedCreatedAt=0;
async function boot(){try{await ensureFirebase();$("#connection").textContent="Firebase 已連線";$("#clearSelected").onclick=clearSelected;$("#submit").onclick=submit;onValue(dbRef("game"),s=>{game=s.val()||{};render();});}catch(e){$("#connection").textContent="Firebase 未連線";msg(e.message,"error");show("#waiting");}}
function currentRoundNo(){const p=game.meta?.phase||"";return p.startsWith("round2")?2:p.startsWith("round1")?1:0;}
function render(){const rn=currentRoundNo();show("#waiting",!rn);show("#workspace",Boolean(rn));if(!rn)return;const round=game.rounds?.[rn];if(!round)return;$("#roundTitle").textContent=`ROUND ${rn}`;const check=round.result?.checkedAt||0;if(syncedRound!==rn||syncedCheck!==check||syncedCreatedAt!==(round.createdAt||0)){submission={...(round.submission||{})};for(const [pid,cell] of Object.entries(round.anchors||{}))submission[cell]=pid;selected=null;syncedRound=rn;syncedCheck=check;syncedCreatedAt=round.createdAt||0;}const players=activePlayers(game),holes=new Set(round.holes||[]),res=round.result?.byPlayer||{},anchorByCell=Object.fromEntries(Object.entries(round.anchors||{}).map(([pid,cell])=>[cell,pid]));const m=$("#matrix");m.style.gridTemplateColumns=`repeat(${round.size},auto)`;m.innerHTML="";for(let r=0;r<round.size;r++)for(let c=0;c<round.size;c++){const k=`${r},${c}`,d=document.createElement("button");d.type="button";d.className="cell";d.dataset.cell=k;if(holes.has(k)){d.classList.add("hole");d.textContent="✦";d.disabled=true;}else{const pid=submission[k],p=players.find(x=>x.id===pid);if(p)d.textContent=numberText(p.number);if(anchorByCell[k]){d.classList.add("anchor");d.title="固定定位玩家";d.disabled=true;}if(pid&&res[pid])d.classList.add(res[pid].ok?"blue":"red");if(selected===k)d.classList.add("selected");if(!anchorByCell[k])d.onclick=()=>{selected=k;render();};}m.appendChild(d);}const used=new Set(Object.values(submission));$("#palette").innerHTML="";for(const p of players){const b=document.createElement("button");b.type="button";b.className="player-chip"+(used.has(p.id)?" used":"");b.textContent=numberText(p.number);b.disabled=used.has(p.id)&&submission[selected]!==p.id;b.onclick=()=>assign(p.id);$("#palette").appendChild(b);}$("#placedCount").textContent=`已放置 ${used.size} / ${players.length}`;}
function assign(pid){if(!selected){msg("請先點選一個矩陣格子。","error");return;}const rn=currentRoundNo(),round=game.rounds?.[rn];if(Object.values(round?.anchors||{}).includes(selected)){msg("這是固定定位格，不能修改。","error");return;}for(const k of Object.keys(submission))if(submission[k]===pid)delete submission[k];submission[selected]=pid;render();}
function clearSelected(){if(selected){const rn=currentRoundNo(),round=game.rounds?.[rn];if(Object.values(round?.anchors||{}).includes(selected)){msg("固定定位格不能清除。","error");return;}delete submission[selected];render();}}
async function submit(){const rn=currentRoundNo(),round=game.rounds?.[rn],players=activePlayers(game);if(!round)return;const count=new Set(Object.values(submission)).size;if(count!==players.length){msg(`還有 ${players.length-count} 位玩家尚未放入矩陣。`,"error");return;}const result=evaluateSubmission(players,round,submission);const updates={};updates[`rounds/${rn}/submission`]=submission;updates[`rounds/${rn}/result`]=result;if(result.allCorrect)updates[`meta/phase`]=rn===1?"round1_done":"round2_done";await update(dbRef("game"),updates);msg(result.allCorrect?"全部條件成立！回合完成。":`本次 ${result.correct}/${result.total} 人條件成立，請看投影幕找紅色位置。`,result.allCorrect?"ok":"");}
boot();
