import {ensureFirebase,dbRef,onValue,get,update,currentUid} from "./firebase.js";
import {$,show,msg,activePlayers,numberText} from "./app-common.js";
import {evaluateSubmission} from "./game-engine.js";
let game={},myId=null,selected=null,submission={},syncedRound=0,syncedCheck=0;
async function boot(){try{await ensureFirebase();const uid=currentUid();myId=(await get(dbRef(`game/ownerIndex/${uid}`))).val()||null;$("#clearSelected").onclick=clearSelected;$("#submit").onclick=submit;onValue(dbRef("game"),s=>{game=s.val()||{};render();});}catch(e){msg(e.message,"error");show("#denied");}}
function currentRoundNo(){const p=game.meta?.phase||"";return p.startsWith("round2")?2:p.startsWith("round1")?1:0;}
function authorized(){return myId&&game.meta?.leaderPlayerId===myId&&["round1","round2"].includes(game.meta?.phase);}
function render(){if(!authorized()){show("#workspace",false);show("#denied");return;}show("#denied",false);show("#workspace");const rn=currentRoundNo(),round=game.rounds?.[rn];if(!round)return;$("#roundTitle").textContent=`ROUND ${rn}`;const check=round.result?.checkedAt||0;if(syncedRound!==rn||syncedCheck!==check){submission={...(round.submission||{})};syncedRound=rn;syncedCheck=check;}const players=activePlayers(game),holes=new Set(round.holes||[]),res=round.result?.byPlayer||{};const m=$("#matrix");m.style.gridTemplateColumns=`repeat(${round.size},auto)`;m.innerHTML="";for(let r=0;r<round.size;r++)for(let c=0;c<round.size;c++){const k=`${r},${c}`,d=document.createElement("button");d.type="button";d.className="cell";d.dataset.cell=k;if(holes.has(k)){d.classList.add("hole");d.textContent="✦";d.disabled=true;}else{const pid=submission[k],p=players.find(x=>x.id===pid);if(p)d.textContent=numberText(p.number);if(pid&&res[pid])d.classList.add(res[pid].ok?"blue":"red");if(selected===k)d.classList.add("selected");d.onclick=()=>{selected=k;render();};}m.appendChild(d);}const used=new Set(Object.values(submission));$("#palette").innerHTML="";for(const p of players){const b=document.createElement("button");b.type="button";b.className="player-chip"+(used.has(p.id)?" used":"");b.textContent=numberText(p.number);b.disabled=used.has(p.id)&&submission[selected]!==p.id;b.onclick=()=>assign(p.id);$("#palette").appendChild(b);}$("#placedCount").textContent=`已放置 ${used.size} / ${players.length}`;}
function assign(pid){if(!selected){msg("請先點選一個矩陣格子。","error");return;}for(const k of Object.keys(submission))if(submission[k]===pid)delete submission[k];submission[selected]=pid;render();}
function clearSelected(){if(selected){delete submission[selected];render();}}
async function submit(){const rn=currentRoundNo(),round=game.rounds?.[rn],players=activePlayers(game);if(!round)return;const count=new Set(Object.values(submission)).size;if(count!==players.length){msg(`還有 ${players.length-count} 位玩家尚未放入矩陣。`,"error");return;}const result=evaluateSubmission(players,round,submission);const updates={};updates[`rounds/${rn}/submission`]=submission;updates[`rounds/${rn}/result`]=result;if(result.allCorrect)updates[`meta/phase`]=rn===1?"round1_done":"round2_done";await update(dbRef("game"),updates);msg(result.allCorrect?"全部條件成立！回合完成。":`本次 ${result.correct}/${result.total} 人條件成立，請看投影幕找紅色位置。`,result.allCorrect?"ok":"");}
boot();
